name: Test

on:
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - name: "Checkout the repository"
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: "Install dependencies"
      run: |
        python3 -m pip install uv --no-cache-dir
        python3 -m uv pip install -r requirements.txt pytest --no-cache-dir

    - name: "Test with pytest"
      env:
        SPEECH_REGION: ${{ secrets.SPEECH_REGION }}
        SPEECH_KEY: ${{ secrets.SPEECH_KEY }}
      run: |
        pytest
